
[dependency_config_structure]
config_spec_version = 1.0
config_version = 1.0
display_name = "DirectX End User Runtime"
sha_256_hash = "2cf71d098c608c56e07f4655855a886c3102553f648df88458df616b26fd612f"
download_links = ["https://download.microsoft.com/download/1/7/1/1718CCC4-6315-4D8E-9543-8E28A4E18C4C/dxwebsetup.exe"]

[dependency_config_structure.command]
executable = "dxwebsetup.exe"
executable_args = ["/Q"]
executable_method = ["non_halting"]

[[dependency_config_structure.compatible_projects]]
display_name = "AlterWare"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare II 2009"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare III 2011"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops III"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Advanced Warfare"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Ghosts"
    