
[dependency_config_structure]
config_spec_version = 1.0
config_version = 1.0
display_name = "2012_x86"
sha_256_hash = "b924ad8062eaf4e70437c8be50fa612162795ff0839479546ce907ffa8d6e386"
download_links = ["https://github.com/Mythical-Github/tackle_box/raw/refs/heads/main/redists/2012_x86.exe"]

[dependency_config_structure.command]
executable = "2012_x86.exe"
executable_args = ["/install", "/quiet", "/norestart"]
  
[[dependency_config_structure.compatible_projects]]
display_name = "Plutonium"
  
[[dependency_config_structure.compatible_projects]]
display_name = "Aurora"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: World at War"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare III 2011"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops II"
