
[project_config_structure]
config_spec_version = 1.0
config_version = 1.0

[project_config_structure.project_info]
display_name = "AlterWare"
home_page = "https://alterware.dev/"
git_repo_urls = ["https://github.com/alterware", "https://git.alterware.dev/AlterWare"]
community_urls = ["https://forum.alterware.dev/", "https://discord.gg/2ETE8engZM"]
documentation_urls = ["https://forum.alterware.dev/docs"]

[[project_config_structure.project_info.downloads_information]]
file_display_name = "AlterWare Launcher"
download_urls = ["https://github.com/mxve/alterware-launcher/releases/latest/download/alterware-launcher-x86_64-pc-windows-msvc.zip"]
os = "Windows"
